# Generated by Django 3.2.12 on 2024-03-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=90)),
                ('course_id', models.IntegerField()),
                ('course_details', models.CharField(max_length=100)),
                ('course_amount', models.IntegerField()),
                ('course_feedback', models.CharField(max_length=100)),
            ],
        ),
    ]
